// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure that matches your types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          domain: string
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          domain: string
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          domain?: string
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          email: string
          name: string
          phone: string | null
          role: 'volunteer' | 'participant' | 'board_member' | 'admin'
          department: string
          organization_id: string
          netzwerk_city_id: string | null
          permissions: string[]
          avatar: string | null
          is_active: boolean
          is_verified: boolean
          status: 'online' | 'away' | 'offline'
          last_login: string | null
          created_at: string
          years_of_activity: number[]
          profile: Json
          gamification: Json
        }
        Insert: {
          id: string
          email: string
          name: string
          phone?: string | null
          role: 'volunteer' | 'participant' | 'board_member' | 'admin'
          department: string
          organization_id: string
          netzwerk_city_id?: string | null
          permissions?: string[]
          avatar?: string | null
          is_active?: boolean
          is_verified?: boolean
          status?: 'online' | 'away' | 'offline'
          last_login?: string | null
          created_at?: string
          years_of_activity?: number[]
          profile?: Json
          gamification?: Json
        }
        Update: {
          id?: string
          email?: string
          name?: string
          phone?: string | null
          role?: 'volunteer' | 'participant' | 'board_member' | 'admin'
          department?: string
          organization_id?: string
          netzwerk_city_id?: string | null
          permissions?: string[]
          avatar?: string | null
          is_active?: boolean
          is_verified?: boolean
          status?: 'online' | 'away' | 'offline'
          last_login?: string | null
          created_at?: string
          years_of_activity?: number[]
          profile?: Json
          gamification?: Json
        }
      }
      netzwerk_cities: {
        Row: {
          id: string
          name: string
          country: string
          organization_id: string
          coordinators: string[]
          projects: string[]
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          country: string
          organization_id: string
          coordinators?: string[]
          projects?: string[]
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          country?: string
          organization_id?: string
          coordinators?: string[]
          projects?: string[]
          created_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          title: string
          description: string
          status: 'planning' | 'active' | 'completed' | 'on_hold'
          priority: 'low' | 'medium' | 'high' | 'urgent'
          organization_id: string
          netzwerk_city_id: string | null
          manager_id: string
          assigned_volunteers: string[]
          participants: string[]
          start_date: string
          end_date: string | null
          budget: number | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          status?: 'planning' | 'active' | 'completed' | 'on_hold'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          organization_id: string
          netzwerk_city_id?: string | null
          manager_id: string
          assigned_volunteers?: string[]
          participants?: string[]
          start_date: string
          end_date?: string | null
          budget?: number | null
          tags?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          status?: 'planning' | 'active' | 'completed' | 'on_hold'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          organization_id?: string
          netzwerk_city_id?: string | null
          manager_id?: string
          assigned_volunteers?: string[]
          participants?: string[]
          start_date?: string
          end_date?: string | null
          budget?: number | null
          tags?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      courses: {
        Row: {
          id: string
          title: string
          description: string
          instructor: string
          duration: number
          difficulty: 'beginner' | 'intermediate' | 'advanced'
          category: string
          organization_id: string
          modules: Json
          enrolled_users: string[]
          completed_users: string[]
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          instructor: string
          duration: number
          difficulty?: 'beginner' | 'intermediate' | 'advanced'
          category: string
          organization_id: string
          modules?: Json
          enrolled_users?: string[]
          completed_users?: string[]
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          instructor?: string
          duration?: number
          difficulty?: 'beginner' | 'intermediate' | 'advanced'
          category?: string
          organization_id?: string
          modules?: Json
          enrolled_users?: string[]
          completed_users?: string[]
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      community_posts: {
        Row: {
          id: string
          title: string
          content: string
          author_id: string
          organization_id: string
          category: string
          tags: string[]
          likes: number
          liked_by: string[]
          is_pinned: boolean
          is_moderated: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          content: string
          author_id: string
          organization_id: string
          category: string
          tags?: string[]
          likes?: number
          liked_by?: string[]
          is_pinned?: boolean
          is_moderated?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          content?: string
          author_id?: string
          organization_id?: string
          category?: string
          tags?: string[]
          likes?: number
          liked_by?: string[]
          is_pinned?: boolean
          is_moderated?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      community_replies: {
        Row: {
          id: string
          content: string
          author_id: string
          post_id: string
          parent_reply_id: string | null
          likes: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          content: string
          author_id: string
          post_id: string
          parent_reply_id?: string | null
          likes?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          content?: string
          author_id?: string
          post_id?: string
          parent_reply_id?: string | null
          likes?: number
          created_at?: string
          updated_at?: string
        }
      }
      chat_conversations: {
        Row: {
          id: string
          participants: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          participants: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          participants?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      chat_messages: {
        Row: {
          id: string
          conversation_id: string
          sender_id: string
          content: string
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          conversation_id: string
          sender_id: string
          content: string
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          conversation_id?: string
          sender_id?: string
          content?: string
          is_read?: boolean
          created_at?: string
        }
      }
      store_products: {
        Row: {
          id: string
          name: string
          description: string
          price: number
          original_price: number | null
          category: string
          images: string[]
          in_stock: boolean
          stock_quantity: number
          rating: number
          review_count: number
          tags: string[]
          specifications: Json | null
          is_digital: boolean
          organization_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description: string
          price: number
          original_price?: number | null
          category: string
          images?: string[]
          in_stock?: boolean
          stock_quantity?: number
          rating?: number
          review_count?: number
          tags?: string[]
          specifications?: Json | null
          is_digital?: boolean
          organization_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          price?: number
          original_price?: number | null
          category?: string
          images?: string[]
          in_stock?: boolean
          stock_quantity?: number
          rating?: number
          review_count?: number
          tags?: string[]
          specifications?: Json | null
          is_digital?: boolean
          organization_id?: string
          created_at?: string
          updated_at?: string
        }
      }
      activity_logs: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string
          points: number
          date: string
          project_type: string
          role_in_project: string
          project_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description: string
          points: number
          date: string
          project_type: string
          role_in_project: string
          project_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          description?: string
          points?: number
          date?: string
          project_type?: string
          role_in_project?: string
          project_id?: string | null
          created_at?: string
        }
      }
      points_history: {
        Row: {
          id: string
          user_id: string
          date: string
          reason: string
          points: number
          type: 'earned' | 'redeemed'
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date: string
          reason: string
          points: number
          type: 'earned' | 'redeemed'
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          reason?: string
          points?: number
          type?: 'earned' | 'redeemed'
          created_at?: string
        }
      }
      project_participations: {
        Row: {
          id: string
          user_id: string
          project_id: string
          project_name: string
          role: string
          year: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          project_id: string
          project_name: string
          role: string
          year: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          project_id?: string
          project_name?: string
          role?: string
          year?: number
          created_at?: string
        }
      }
      course_enrollments: {
        Row: {
          id: string
          user_id: string
          course_id: string
          enrolled_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          enrolled_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          enrolled_at?: string
        }
      }
      watched_courses: {
        Row: {
          id: string
          user_id: string
          course_id: string
          course_title: string
          completed_date: string
          points_earned: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          course_id: string
          course_title: string
          completed_date: string
          points_earned: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          course_id?: string
          course_title?: string
          completed_date?: string
          points_earned?: number
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

